"""Removed foreign key

Revision ID: 17847ff029ab
Revises: dd9cebea6429
Create Date: 2018-02-05 11:45:19.494777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17847ff029ab'
down_revision = 'dd9cebea6429'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('pitches_user_id_fkey', 'pitches', type_='foreignkey')
    op.drop_column('pitches', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('pitches_user_id_fkey', 'pitches', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
