"""Edited Comment class

Revision ID: 37051a21bf7c
Revises: 232ca97cae49
Create Date: 2018-02-05 23:47:22.025533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37051a21bf7c'
down_revision = '232ca97cae49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('title', sa.String(), nullable=True))
    op.drop_column('comments', 'author')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('author', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('comments', 'title')
    # ### end Alembic commands ###
